apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-x-chartmuseum
  labels:
    app: jenkins-x-chartmuseum
    jenkins.io/chart-release: jenkins-x
    jenkins.io/namespace: jx
    jenkins.io/version: 2.0.1624
    release: jenkins-x
  namespace: jx
spec:
  volumeMode: Filesystem
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins-x-chartmuseum
    namespace: jx
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /var/nfsshare/jenkins-x-chartmuseum
    server: 192.168.56.104
    readOnly: false    
