apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-x-docker-registry
  labels:
    app: jenkins-x-docker-registry
    chart: docker-registry-1.5.0
    heritage: Tiller
    jenkins.io/chart-release: jenkins-x
    jenkins.io/namespace: jx
    jenkins.io/version: 2.0.1624
    release: jenkins-x
  namespace: jx
spec:
  volumeMode: Filesystem
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins-x-docker-registry
    namespace: jx

  accessModes:
    - ReadWriteOnce
  nfs:
    path: /var/nfsshare/jenkins-x-docker-registry
    server: 192.168.56.104
    readOnly: false
