apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    app: jenkins
    chart: jenkins-0.10.38
    heritage: Tiller
    jenkins.io/chart-release: jenkins-x
    jenkins.io/namespace: jx
    jenkins.io/version: 2.0.1624
    release: jenkins-x
  namespace: jx
spec:
  volumeMode: Filesystem
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins
    namespace: jx
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /var/nfsshare/jenkins
    server: 192.168.56.104
    readOnly: false
